### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by ahmetcetin** [brumm/tako#22]
When using with [GitHub-Dark](https://github.com/StylishThemes/GitHub-Dark), text is not readable. Any chance to support dark theme?

**Comment by brumm** [comment]
Sure! What would one need to do to support this?

**Comment by ahmetcetin** [comment]
wow, tbh, i didn't expect that you would like to do it. Anyways, I think first you should add options page to your extension as shown here:

https://developer.chrome.com/extensions/options

Then you can add one of the css files (or add all as option) into the code viewer window:

https://github.com/StylishThemes/GitHub-Dark/tree/master/themes/src/github

My favourite is One Dark, but it's just my taste.

**Comment by brumm** [comment]
Wait, sorry, I didn't read your initial issue closely enough. This seems to be about syntax highlight in the preview, I assumed this was about the text of the entire extension.

I'd be up for adding the relevant css classes to support the github-dark extension in general, but I'm not sure this would work for the preview text.

For thatm I'm planning the make the preview text theme and style configurable in general via an options page, but that's still a while off :)

**Comment by ahmetcetin** [comment]
Look how it looks atm:
<img width="1340" alt="brumm_tako__Tako_replaces_the_default_Github_repository_file_list_with_an_expandable_file_tree_for_rapid_exploration_of_repositories" src="https://user-images.githubusercontent.com/5046786/79133016-9facc100-7dab-11ea-8ba2-53522d86b48b.png">

File list is handled with GitHub-Dark, just the preview text part is not.

I really love this extension, soon I love to ditch Octotree finally.

**Comment by marchingon12** [comment]
@ahmetcetin just a quick suggestion for you: instead of using GitHub-Dark, you could use "Dark Reader" for [Firefox](https://addons.mozilla.org/en-US/firefox/addon/darkreader/) or [Chromium](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en)-based browsers. The preview or rather the whole GitHub page is rendered perfectly in dark mode (Dark Reader mode: Dynamic). Look at the screenshot below to confirm.

![image](https://user-images.githubusercontent.com/41235480/94615513-715a6980-0297-11eb-867c-a9fa31c6b581.png)

Of course, using Dark Reader isn't going to be as easy to customize or configure if you want to use custom themes on your GitHub pages, but it works.
Also kudos to @brumm for forked repo fix!

You can find the CSS code under: Dark Reader extension button> Settings > 🛠️  DevTools > use Ctrl+F to search 'github'.

Edit: I noticed that you're using the old GitHub design instead of the new one... could you maybe do a screenshot of the new GitHub design with GitHub-Dark as well? Just for reference.

**Comment by brumm** [comment]
Hey folks, @marchingon12's solutions seems to work nicely! I'm going to close this issue, because I decided to not support any dark mode until github comes out with their own. In the meantime, solutions like "Dark Reader" exist 😄
